// SPDX-License-Identifier: Apache-2.0
// Package workflows defines the Temporal workflows that orchestrate
// microVM lifecycle operations. Workflows describe WHAT should happen
// (in terms of activities) and let Temporal handle retries, timeouts,
// and crash recovery. Activities (in ./activities) do the actual work.
package workflows

import (
	"time"
)

// MicroVMSpec describes a microVM to launch. Mirrors the request body
// the Cloudflare Worker receives from the dashboard.
type MicroVMSpec struct {
	Template    string `json:"template"`     // e.g. "base", "code-interpreter"
	VCPUCount   int    `json:"vcpu_count"`   // logical CPUs
	MemMiB      int    `json:"mem_mib"`      // memory in MiB
	DiskGiB     int    `json:"disk_gib"`     // disk in GiB
	TTLSeconds  int    `json:"ttl_seconds"`  // 0 = no TTL
	OrgID       string `json:"org_id"`
	RequestedBy string `json:"requested_by"` // user id / token id
	Region      string `json:"region,omitempty"` // preferred agent region
}

// MicroVMResult is what the workflow returns to the caller (via Temporal
// query or final completion).
type MicroVMResult struct {
	VMID       string    `json:"vm_id"`
	IP         string    `json:"ip"`
	State      string    `json:"state"` // running, paused, hibernated, deleted
	WorkerID   string    `json:"worker_id"`
	StartedAt  time.Time `json:"started_at"`
	FinishedAt time.Time `json:"finished_at,omitempty"`
	Duration   string    `json:"duration,omitempty"`
	Error      string    `json:"error,omitempty"`
}

// LaunchMicroVMInput is the input to LaunchMicroVMWorkflow.
type LaunchMicroVMInput struct {
	Spec       MicroVMSpec `json:"spec"`
	WorkflowID string      `json:"workflow_id"` // generated by caller; used as VMID
}

// LaunchMicroVMOutput is what the workflow returns when the VM is ready.
type LaunchMicroVMOutput = MicroVMResult

// Activity timeouts. Activities do the heavy work (Firecracker calls,
// snapshot restore, etc.) and may take minutes. Heartbeats keep Temporal
// informed that the activity is still alive.
const (
	// Long: launching a microVM from a baked snapshot can take 30s-2min.
	LaunchActivityTimeout = 5 * time.Minute
	// Pause/Resume are sub-second on warm hosts.
	ShortActivityTimeout = 30 * time.Second
	// Snapshot can take longer for large memory snapshots.
	SnapshotActivityTimeout = 10 * time.Minute
	// Delete is fast: stop the VM, remove disk.
	DeleteActivityTimeout = 30 * time.Second
	// Heartbeat must be sent at least this often or Temporal marks
	// the activity as timed out.
	HeartbeatTimeout = 1 * time.Minute
)

// Retry policy for infra-level failures (network, missing template, OOM).
// Exponential backoff with jitter. Caps at 3 attempts so a bad request
// doesn't pin a worker forever.
var DefaultRetryPolicy = map[string]interface{}{
	"initial_interval":    5 * time.Second,
	"backoff_coefficient": 2.0,
	"maximum_interval":    1 * time.Minute,
	"maximum_attempts":    3,
}
